# -*- mode: python ; coding: utf-8 -*-
import os
BLOCK_CIPHER = None

PROJECT_ROOT = os.path.abspath(".")
FRONTEND_DIST = os.path.join(PROJECT_ROOT, "frontend", "dist")

a = Analysis(
    [os.path.join(PROJECT_ROOT, "main.py")],
    pathex=[PROJECT_ROOT],
    binaries=[],
    datas=[
        (os.path.join(FRONTEND_DIST, "index.html"), "frontend/dist"),
        (os.path.join(FRONTEND_DIST, "assets"), "frontend/dist/assets"),
    ],
    hiddenimports=[
        "uvicorn",
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "fastapi",
        "sqlalchemy",
        "sqlalchemy.sql.default_comparator",
        "openai",
        "httpx",
        "cryptography",
        "cryptography.fernet",
        "pydantic",
        "yaml",
        "backend.main",
        "backend.config",
        "backend.database",
        "backend.di",
        "backend.security",
        "backend.workspace",
        "backend.file_processor",
        "backend.models",
        "backend.models.agent",
        "backend.models.conversation",
        "backend.models.conversation_file",
        "backend.models.message",
        "backend.models.model_provider",
        "backend.models.tool",
        "backend.models.tool_category",
        "backend.models.cluster",
        "backend.models.mcp_server",
        "backend.routers",
        "backend.routers.agents",
        "backend.routers.categories",
        "backend.routers.chat",
        "backend.routers.clusters",
        "backend.routers.mcp_router",
        "backend.routers.models",
        "backend.routers.settings",
        "backend.routers.tools",
        "backend.services",
        "backend.services.agent_engine",
        "backend.services.agent_service",
        "backend.services.base",
        "backend.services.cluster_engine",
        "backend.services.cluster_service",
        "backend.services.local_ops",
        "backend.services.mcp_manager",
        "backend.services.model_pool",
        "backend.services.plugin_manager",
        "backend.services.tool_factory",
        "backend.services.tool_loader",
        "backend.services.tool_registry",
        "backend.services.tool_service",
        "backend.tools_builtin",
        "backend.tools_builtin.calculator",
        "backend.tools_builtin.command_runner",
        "backend.tools_builtin.dir_lister",
        "backend.tools_builtin.file_reader",
        "backend.tools_builtin.file_writer",
        "backend.tools_builtin.http_request",
        "backend.tools_builtin.web_search",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "numpy",
        "pandas",
        "PIL",
        "scipy",
        "torch",
        "tensorflow",
        "notebook",
        "jupyter",
        "setuptools",
        "pip",
        "wheel",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="AI Agent",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    contents_directory=".",
)